# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d3d8e3f76b40842433ea58f983e2dd2924c8c7b1b68867d32c7aa5f710ab24ef2c2b2f5aa3d3036a84dd91a754d7947f5cc126c6de6fc6fcd4dc40343feb49b

test:
  secret_key_base: dc2710b95bc732b080809d9d0af7b2ea52d8f3c57fed9bc084177353b58b3816012cbaf9bccd1a2dc70d8cc47605b77c4a6105f8d08bfc916436af20c9d759e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
