# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56aa4c70d4facba1ac898d5813839deed0004320f6c84c27842c5722700a610d699cd9de58a56899c12a8a6918935d658e487efeda8543ff05744cf80d26afc6

test:
  secret_key_base: 1ad49fdd1da538209ba41a762137a50c9bea54f9e2e4670daf312b7147df6fffe82053ef4dca497975a88b821c818c266603dc22a1d4388b75b64b7eb8f075a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
